swagger: "2.0"
info:
  title: Upload API LOL Info
  description: API Gateway for posting League of Legends data each path 
  version: 1.0.0
host: us-east4-big-data-lol.cloudfunctions.net
schemes:
  - https
paths:
  /post_json:
    post:
      summary: Upload JSON data
      operationId: postJson
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: The JSON champions data to upload
          required: true
          schema:
            type: object
      x-google-backend:
        address: https://us-east4-big-data-lol.cloudfunctions.net/post_bucket_json
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Error
          schema:
            type: object
            properties:
              error:
                type: string

                
  /post_images:
    post:
      summary: Upload images
      operationId: postImagesChamps
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: images
          in: formData
          description: The images to upload
          required: true
          type: array
          items:
            type: string
            format: binary
      x-google-backend:
        address: https://us-east4-big-data-lol.cloudfunctions.net/post_bucket_images
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Error
          schema:
            type: object
            properties:
              error:
                type: string


